apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  labels:
    kubernetes.io/metadata.name: acoustic-stick
  name: acoustic-stick
spec:
  cordoned: false
  imagePullPolicies:
    - Always
    - Never
    - IfNotPresent
  ingressOptions:
    hostnameCollisionScope: Tenant
  limitRanges: {}
  namespaceOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: acoustic-stick
    forbiddenAnnotations: {}
    forbiddenLabels: {}
    quota: 10
  networkPolicies:
    items:
      - egress:
          - {}
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    capsule.clastix.io/tenant: acoustic-stick
              - namespaceSelector:
                  matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: In
                      values:
                        - ingress-nginx
              - namespaceSelector:
                  matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: In
                      values:
                        - kube-system
              - podSelector:
                  matchLabels:
                    managed-by: operator
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
  owners:
    - clusterRoles:
        - admin
        - capsule-namespace-deleter
      name: bob
      kind: User  # This grants user 'bob' administrative access to the Tenant
      proxySettings:
        - kind: IngressClasses
          operations:
            - List
        - kind: Nodes
          operations:
            - List
        - kind: StorageClasses
          operations:
            - List
        - kind: PriorityClasses
          operations:
            - List
        - kind: PersistentVolumes
          operations:
            - List
  podOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: acoustic-stick
  preventDeletion: false
  resourceQuotas:
    items:
      - hard:
          limits.cpu: '2'
          limits.memory: 2Gi
          pods: '10'
          requests.storage: 10Gi
    scope: Tenant
  serviceOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: acoustic-stick
    allowedServices:
      externalName: true
      loadBalancer: false
      nodePort: true
    forbiddenAnnotations: {}
    forbiddenLabels: {}
